<?php
/**
 * Formloader: Auto Generated Form Configuration
 * --- Please do not edit this file directly... your changes will be overridden! ---
 */
return array(
		'validation' => array(
				array(
						'group',
						'Group:',
						array('fuel.required','fuel.valid_string[alpha]'),
				),
				array(
						'name',
						'Action Name:',
						array('fuel.required','fuel.valid_string[alpha,dashes]'),
				),
		),
		'route_success' => 'HMVC::formloader/api/save/actions',
);
