<?php
/**
 * Formloader: Auto Generated Form Configuration
 * --- Please do not edit this file directly... your changes will be overridden! ---
 */
return array(
		'option_calls' => array(
				'ignored_groups' => 'Formloader_Scaffold::ignored_groups',
		),
		'route_success' => 'Formloader_Scaffold::ignored_groups',
);
