<?php
/**
 * Formloader: Auto Generated Form Configuration
 * --- Please do not edit this file directly... your changes will be overridden! ---
 */
return array(
		'validation' => array(
				array('group','Group','required|valid_string[alpha,numeric]'),
				array(
						'name',
						'Action Name',
						'required|valid_string[alpha,dashes,numeric]',
				),
		),
);
