<?php
/**
 * Formloader: Auto Generated Form Configuration
 * --- Please do not edit this file directly... your changes will be overridden! ---
 */
return array(
		'validation' => array(
				array('group','Group','required|valid_string[alpha]'),
				array(
						'name',
						'Fieldset Name',
						'required|valid_string[alpha,dashes]',
				),
		),
		'selects' => array('use_legend')
);
