<?php
/**
 * Formloader: Auto Generated Form Configuration
 * --- Please do not edit this file directly... your changes will be overridden! ---
 */
return array(
		'validation' => array(
				array('group','Group','required|valid_string[alpha]'),
				array(
						'name',
						'Field Name',
						'required|valid_string[alpha,dashes]',
				),
		),
		'selects' => array('attributes.type','options'),
		'route_success' => 'HMVC::formloader/api/save/fields',
);
